spring:
  datasource:
    url: jdbc:mysql://47.92.81.33:3306/springboot?useUnicode=true&characterEncoding=utf-8&&serverTimezone=GMT%2B8
    username: root
    password: 110110
    driver-class-name: com.mysql.cj.jdbc.Driver